### PR TITLE
Add support for Linux ARM64

### LINKED ISSUE #1: Upgrade bwa to latest to support linux arm64/aarch64
We are supporting the BioConductor on Linux aarch64:

- [Bioc-devel] Support for Linux ARM64: https://stat.ethz.ch/pipermail/bioc-devel/2023-January/019398.html

But hit the issue on RBWA: https://github.com/Yikun/BBS/issues/20 .

Actually, the upstream bwa already support the linux aarch64 [1] since 2022 and also enable the linux arm CI [2].

Could you upgrade bwa to latest to include [1][2]? @Jfortin1

Please let us know if you need any help! Thanks

[1] https://github.com/lh3/bwa/pull/359
[2] https://github.com/lh3/bwa/pull/367

### PR DESCRIPTION
**Pull request by martin-g**
Apply https://patch-diff.githubusercontent.com/raw/lh3/bwa/pull/359.patch from https://github.com/lh3/bwa/pull/359

Fixes #1

### CODE REVIEW

**Comment by martin-g** [comment]
```
 ~/bbs-3.17-bioc/R/bin/R CMD build Rbwa
* checking for file ‘Rbwa/DESCRIPTION’ ... OK
* preparing ‘Rbwa’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘Rbwa_1.3.0.tar.gz’

biocbuild@kunpeng1:~/git$ ~/bbs-3.17-bioc/R/bin/R CMD check Rbwa_1.3.0.tar.gz 
* using log directory ‘/home/biocbuild/git/Rbwa.Rcheck’
* using R Under development (unstable) (2023-01-14 r83615)
* using platform: aarch64-unknown-linux-gnu (64-bit)
* R was compiled by
    gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
    GNU Fortran (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
* running under: Ubuntu 22.04.1 LTS
* using session charset: UTF-8
* checking for file ‘Rbwa/DESCRIPTION’ ... OK
* this is package ‘Rbwa’ version ‘1.3.0’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .BBSoptions
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘Rbwa’ can be installed ... WARNING
Found the following significant warnings:
  rope.c:282:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  rope.c:283:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  rope.c:291:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  rope.c:292:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  rope.c:293:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  rope.c:312:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  rope.c:313:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  bwashm.c:29:9: warning: ignoring return value of ‘ftruncate’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  bwashm.c:66:9: warning: ignoring return value of ‘ftruncate’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
See ‘/home/biocbuild/git/Rbwa.Rcheck/00install.out’ for details.
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking for GNU extensions in Makefiles ... NOTE
GNU make is a SystemRequirements.
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking include directives in Makefiles ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘Rbwa.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 WARNING, 2 NOTEs
See
  ‘/home/biocbuild/git/Rbwa.Rcheck/00check.log’
for details.
```

**Comment by Jfortin1** [comment]
@martin-g Thanks for the PR -- trying on my macbook, and it's complaining:

```
(base) fortinj2:~$ R CMD build Rbwa
* checking for file ‘Rbwa/DESCRIPTION’ ... OK
* preparing ‘Rbwa’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘Rbwa’ ...
** using staged installation
** libs
** arch - 
gcc -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -g -Wall -O2 -c utils.c -o utils.o
gcc -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -g -Wall -O2 -c kthread.c -o kthread.o
gcc -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -g -Wall -O2 -c kstring.c -o kstring.o
make: *** No rule to make target `neon_sse.h', needed by `ksw.o'.  Stop.
ERROR: compilation failed for package ‘Rbwa’
* removing ‘/private/var/folders/cc/78yl5p9d5mx2mm77xpmvr9lm0000gn/T/RtmppDpUFK/Rinst834c2afa65c/Rbwa’
      -----------------------------------
ERROR: package installation failed

**Comment by Yikun** [comment]
@martin-g It seems `neon_sse.h` / `scalar_sse.h` forget to add and push?

[1] https://github.com/lh3/bwa/pull/359/files

**Comment by martin-g** [comment]
That's correct! Thanks, @Yikun !
Added the files. @Jfortin1 Please try again!

**Pull request merged**
